/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NdlBackdrop {}
  interface NdlModal {}
  interface NdlModalDefault {}
  interface NdlPanel {
    'header': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNdlBackdropElement extends Components.NdlBackdrop, HTMLStencilElement {}
  var HTMLNdlBackdropElement: {
    prototype: HTMLNdlBackdropElement;
    new (): HTMLNdlBackdropElement;
  };

  interface HTMLNdlModalElement extends Components.NdlModal, HTMLStencilElement {}
  var HTMLNdlModalElement: {
    prototype: HTMLNdlModalElement;
    new (): HTMLNdlModalElement;
  };

  interface HTMLNdlModalDefaultElement extends Components.NdlModalDefault, HTMLStencilElement {}
  var HTMLNdlModalDefaultElement: {
    prototype: HTMLNdlModalDefaultElement;
    new (): HTMLNdlModalDefaultElement;
  };

  interface HTMLNdlPanelElement extends Components.NdlPanel, HTMLStencilElement {}
  var HTMLNdlPanelElement: {
    prototype: HTMLNdlPanelElement;
    new (): HTMLNdlPanelElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'ndl-backdrop': HTMLNdlBackdropElement;
    'ndl-modal': HTMLNdlModalElement;
    'ndl-modal-default': HTMLNdlModalDefaultElement;
    'ndl-panel': HTMLNdlPanelElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NdlBackdrop extends JSXBase.HTMLAttributes<HTMLNdlBackdropElement> {}
  interface NdlModal extends JSXBase.HTMLAttributes<HTMLNdlModalElement> {}
  interface NdlModalDefault extends JSXBase.HTMLAttributes<HTMLNdlModalDefaultElement> {}
  interface NdlPanel extends JSXBase.HTMLAttributes<HTMLNdlPanelElement> {
    'header'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'ndl-backdrop': NdlBackdrop;
    'ndl-modal': NdlModal;
    'ndl-modal-default': NdlModalDefault;
    'ndl-panel': NdlPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


